spring.application.name=viagens-igreja

spring.datasource.url=jdbc:mysql://localhost:3306/viagensigreja_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
