spring.datasource.url=jdbc:postgresql://localhost:5432/igreja_viagens
spring.datasource.username=igreja
spring.datasource.password=igreja

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true